language: ruby
rvm:
  - 2.6
install: 
  - gem install jekyll html-proofer
  - bundle install
script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh
after_success:
  - bundle exec ruby _scripts/deploy.rb
