language: ruby
rvm:
  - 2.2
install: gem install jekyll html-proofer
script: bundle install && bundle exec jekyll build && htmlproofer --assume-extension --url-ignore https://linkedin.com/in/christian-fischer-a89952102 ./_site
