language: ruby
rvm:
  - 2.2
install: 
  - gem install jekyll html-proofer
  - bundle install
script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh
after_success:
  - chmod +x _scripts/deploy.sh
  - _scripts/deploy.sh

sudo: false
addons:
  apt:
    packages:
      - ncftp
